apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: omsorgspenger-journalforing
  namespace: omsorgspenger
  labels:
    team: omsorgspenger
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  kafka:
    pool: {{kafkaPool}}
  strategy:
    type: RollingUpdate
  accessPolicy:
    outbound:
      external:
      {{#each externalHosts as |url|}}
         - host: {{url}}
      {{/each}}
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  env:
  {{#each env}}
    - name: {{@key}}
      value: {{this}}
  {{/each}}
    - name: KAFKA_RAPID_TOPIC
      value: omsorgspenger.k9-rapid-v2
    - name: KAFKA_CONSUMER_GROUP_ID
      value: omsorgspenger-journalforing